// Generated by CoffeeScript 1.3.1

/*
	Here is any custom javascript you need to run.
	To hook into the angular module for creating custom directives, use angular.module('SpokeUtilities') and define directives off it.
	This is the last javascript file loaded.
*/


(function() {



}).call(this);
